### PR TITLE
Improve speed by using Rcpp

### PR DESCRIPTION
**Pull request by kieranjmartin**
Had a go at optimising code. I know theres a bit to do still (package version would need updating), but I wanted feedback at this point. This is now around 40% faster than before. The remaining bottlenecks are caused by subsetting data frames, which is often quite expensive, but is rather difficult to do in rcpp. Technically we could add in data.table to speed that part up, but I'm a little loathe to add data.table, as we'd need to cast data in then out of data.table format.

I could make this significantly faster by pushing the mapply into rcpp, but to do this will need some effort, as I would have to make a handler for every data type the "keys" can be, in particular factor or date. I am also a little concerned about passing out the data frame through c++ as that may cause some bugs: currently the c++ code just returns an index which R then subsets on. I'm confident that if I could get that working then it'd be very fast.

One way to make that easier would be to require the user to only provide keys which are classed character or numeric. I actually think this is not an unreasonable condition, but I can imagine a case where a key is actually in date format. I'm not actually sure we have any tests that we handle dates of different origins correctly on master anyway....

### CODE REVIEW

**Comment by kieranjmartin** [comment]
Urgh and apparently my version of master wasn't quite up to date. Bah!

**Comment by kieranjmartin** [comment]
Ah, good point, I should add unit testing of the c++ code!

**Comment by kieranjmartin** [comment]
@gowerc this now passes build tests. It has testing around all c functions. I would recommend looking at the find_matches test and maybe adding one of your own if you can think of a good one, as that is quite a key function (it's used to avoid merging, which is quite expensive). I also added some extra date testing, because for comparing dates I'm casting them to numeric, and wanted to test this is fine

**Comment by gowerc** [comment]
Ok Looks like there are some issues around brackets in the rcpp code:

```
   Found the following significant warnings:
     indexselect.cpp:77:14: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
     indexselect.cpp:88:33: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
     indexselect.cpp:101:32: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
     indexselect.cpp:115:32: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
```

@kieranjmartin  would you be able to look into this ?

**Comment by kieranjmartin** [comment]
Note that devel should be caught up with master before this is merged

**Comment by gowerc** [comment]
Ok still working on this but an initial comment:

```
identify_extra_rows <- function(DS1, DS2 , KEYS){
  
    DS1   <- DS1[do.call("order", DS1[KEYS]), ]
    DS2   <- DS2[do.call("order", DS2[KEYS]), ]
    DSin  <- factor_to_character(DS1)
    DS2in <- factor_to_character(DS2)

    classtype <- as.character(lapply(DSin[,KEYS], mode))

    index_select <- find_matches(DSin[,KEYS, drop = FALSE], DS2in[,KEYS, drop = FALSE], classtype, length(KEYS))
    list(baseextra   = subset(DS1,!seq(1:nrow(DS1)) %in% index_select[[1]] , KEYS),
         compextra   = subset(DS2,!seq(1:nrow(DS2)) %in% index_select[[2]] , KEYS),
         base_reduce = subset(DS1,seq(1:nrow(DS1)) %in% index_select[[1]]),
         comp_reduce = subset(DS2,seq(1:nrow(DS2)) %in% index_select[[2]]))
}
```

This code was being a bit weird,   in particular `classtype <- as.character(lapply(DSin[,KEYS], mode))` didn't have the `drop=FALSE` so in the case of only 1 variable in KEYS would return a vector equal to the length of nrow.    Additionally  class on numerics can also return integer which your Rcpp code wasn't designed to setup to handle.  To cater for both these issues I have replace this function with:


```
identify_extra_rows <- function(DS1, DS2 , KEYS){

    DS1   <- sort_df(DS1, KEYS)   
    DS2   <- sort_df(DS2, KEYS)   
    DSin  <- factor_to_character(DS1)
    DS2in <- factor_to_character(DS2)
    
    classtype <- as.character(lapply(
        subset_se(DSin, cols = KEYS),
        class
    ))
    classtype[ classtype == "integer"] <- "numeric"
    
    index_select <- find_matches(
        subset_se( DSin, cols = KEYS), 
        subset_se( DS2in, cols = KEYS),
        classtype, 
        length(KEYS)
    )
    
    x <- list(
        baseextra   = subset_se(DS1, -index_select[[1]], KEYS),
        compextra   = subset_se(DS2, -index_select[[2]], KEYS),
        base_reduce = subset_se(DS1,  index_select[[1]]),
        comp_reduce = subset_se(DS2,  index_select[[2]])
    )
    
    return(x)
}
```

As a side note I abstract the sorting code to its own utility function just to ease the readability.  Also I created a new utility function  `subset_se`  which does the same as subset but only standard evaluation,  basically a wrapper  around   `df[  rows , cols , drop = FALSE]`  I wasn't keen on the use of the actual subset function as if `KEYS` was the name of an actual variable in the dataset subset would select that rather than the character vector values of our `KEYS` variable

**Comment by gowerc** [comment]
@kieranjmartin ,   so I don't understand the cpp code well enough to know if this makes sense but am thinking for `find_matches` the following:

- Just return the index of the matches.   Matches can then be selected with df[index] and non matches with df[-index].  Hopefully will reduce code complexity and remove redundant vectors.
- Perhaps then rename as `find_row_match_index` to be explicit in its functionality (or something similar)  likewise perhaps rename the file as well ?

**Comment by gowerc** [comment]
Ok @kieranjmartin ,  Something weird is now going on which I can't work out.  I put together an fairly extensive bench marking test for the changes along side yours in `/utils/benchmarks/benchmark2.R`.

I created 20 numeric variables   of 3million rows then compared a dataset to itself as well as one completely different.  I did the same for 20 character, 20 factor  and 20 of each.  I did this for the current master version of the package and then the one in this branch after your changes.   The current master results were:

```
$num_same - 16.6115
$num_diff - 16.4971

$chr_same - 18.1207
$chr_diff - 18.2392

$fct_same -  16.0621
$fct_diff - 16.1842

$all_same - 34.1566
$all_diff - 34.2347
```

And for the new code

```
$num_same - 9.1408
$num_diff - 8.9272

$chr_same - 12.9573
$chr_diff - 12.9381

$fct_same - 12.637
$fct_diff - 12.7658

$all_same - 32.6541
$all_diff - 31.8025
```

What I can't understand is how we are seeing such substantial benefits in the variables individually yet next to no benefit on the overall ?  I'm wondering if its there some sort of scaling penalty associated with increasing the number of columns ? I couldn't yet work out where this issue is coming from

**Comment by gowerc** [comment]
Ok yer @kieranjmartin ,  theres defo an issue with columns. I did the same benchmark again but this time only doing 1 million observations across 60 columns for each type  and then just 20 of each type for the one with all 3 in one (i.e. every test is just 60 columns).   This was the results for the current master branch:

```
num_same - 7.505
num_diff - 7.225

chr_same - 8.505
chr_diff - 8.394

fct_same - 7.624
fct_diff - 7.529

all_same - 7.868
all_diff - 7.841
```

And the results for the current branch:
```
num_same - 7.109
num_diff - 7.199

chr_same - 11.308
chr_diff - 11.295

fct_same - 10.647
fct_diff - 10.689

all_same - 9.667
all_diff - 9.645
```

So yer, in short the changes have made a big improvement for large numbers of rows but have made things a fair bit worse for increased numbers of columns (which seems to be driven from character comparison).  Considering some labs datasets can be very wide I think we should try and address this.

**Comment by kieranjmartin** [comment]
Hmm, so I had focused on row-wise operation because my exploration had indicated that this was where things were expensive, not column-wise. These results seems to belie that assumption. I wonder if my new merge is actually more expensive when you have lots of columns. I will need to look at the profiler. This may be a pay off that is not easy to solve.

As a note for your changes, it would be useful to add tests which would make my changes fail, as these were passing all tests, so it would be nice to protect. In particular, I think subset is used elsewhere in our code and may be vulnerable to this in general (one easy fix if using subset is just to use X$name rather than just name).

I am unlikely to seriously invest any time in this branch in the short term, it may be worth making separate branches which look at addressing other issues if you happen to have the time.

**Comment by gowerc** [comment]
@kieranjmartin ,

Pending our conversations around performance and the usage of data.table I created a separate PR based off of this branch.   See #35,  I believe we should avoid doing anymore development in this branch until the datatable PR is merged.  I split it out into its own branch as to highlight the specific changes made to convert this branch to DT

**Pull request closed without merging**
