### PR TITLE
Dev config

### PR DESCRIPTION
**Pull request by kieranjmartin**
Note, this should be merged after #35

### CODE REVIEW

**Comment by kieranjmartin** [comment]
@gowerc This currently fails the R checks, so I need to rethink. Basically I want one function you call which gives you all the current options, and you can provide arguments to  to update them. My solution was just to give arguments of ... to the fn, but if you then document the arguments R check doesn't like it

**Comment by kieranjmartin** [comment]
Well, to be fair it gives a warning, not an error, that i document arguments which aren't included. I could just make it so that diffdf_options() resets it, and have diffdf call options("diffdf_options") by default. I guess that would work ok

**Comment by gowerc** [comment]
hmm, do we defo want to move all those options over? Like would it make more sense to keep some of the major ones in the main function still like `warnings` ? 

Also how come the use of the options system over just having a function that returns a list ?

**Comment by kieranjmartin** [comment]
Well, the main reason is that we ideally want the user to be able to set options before doing a bunch of diffdf commands. We could acheive that by saving it as environmental variable, but I figured if we were going to do that we might as well use the options, which exist for this kind of use case.

We could move warnings out, I kind of like the cleaness of this version

**Comment by gowerc** [comment]
@kieranjmartin 

To make life easy for users I'm thinking we should allow for a hybrid / pass through approach. Building on what you've got so far (bear with me here .....)


`options("diffdf_config")`    is the default options set which can be changed by the user

`diffdf_config()` - is then a helper function which contains all the options + documentation


`diffdf( base, compare, keys, ... , .config = diffdf_config()) `    - Then we can allow the user to specify options either via  `...`  or `diffdf_config()`  with `...` taking precidence.


The justification for this being that if a user just wants to stop warnings its nicer (and backwards compatible) to write

```
diffdf( iris, iris,  warnings = FALSE)
```

than

```
diffdf( iris, iris, config = diffdf_config( warnings = FALSE)) 
```

The hybrid approach also allows for templating and minor tweaks to the template

```
opts <- diffdf_config( strict_factor = TRUE, strict_numeric = TRUE, warnings = FALSE)

diffdf( dat1, dat2 , .config = opts)
diffdf(dat1 , dat3,  warnings = TRUE , .config = opts)
```

**Comment by gowerc** [comment]
@kieranjmartin ,

Also can we be consistent in our naming here,  is it configuration or options ?

**Comment by kieranjmartin** [comment]
@gowerc I have mostly actioned your comments. The one thing about the way this works is diffdf_options currently sets the global options, so if you do 

`diffdf(iris, iris, options = diffdf_options(warnings = FALSE))`

then in following invocations of diffdf warnings will be set to FALSE. I could probably make it so that diffdf_options() only updates global options when it's invoked outside of the function, but I think that's more confusing

**Comment by gowerc** [comment]
@kieranjmartin , 

I've ported the most basic parts of this into #67  but I'm just not too sure about the overall implementation. I'm not massively keen on using the global options system. I think we should discuss this some more when you are back in the office.

For now in #67 I have gone with the options as a list object approach but allow the user to specify it either in the `...` or via the `opts=list(...)` arguments to diffdf. 

I have also moved out several of the arguments to the print function which aren't relevant for the main processing of diffdf. 

I have also replaced `warnings` with `onfailure` which has the options of  error/ warning / message / nothing as it dawned on me that the current warning based approach may not fail CICD jobs

**Pull request closed without merging**
